version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: hoangnghia00
      RABBITMQ_DEFAULT_PASS: hoangnghia
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_USER: hoangnghia00
      RABBITMQ_PASS: hoangnghia
    depends_on:
      - mongo
      - rabbitmq

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order
    ports:
      - "3002:3002"
    environment:
      RABBITMQ_USER: hoangnghia00
      RABBITMQ_PASS: hoangnghia
    depends_on:
      - mongo
      - rabbitmq

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_USER: hoangnghia00
      RABBITMQ_PASS: hoangnghia
    depends_on:
      - mongo
      - rabbitmq

  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "3003:3003"
    environment:
      RABBITMQ_USER: hoangnghia00
      RABBITMQ_PASS: hoangnghia
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-data:
